# Generated by Django 3.0.3 on 2020-02-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yandex_kassa.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yandex_kassa', '0005_auto_20160109_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cps_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта плательщика'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cps_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон плательщика'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_number',
            field=models.CharField(default=yandex_kassa.utils.get_uuid, max_length=64, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fail_url',
            field=models.URLField(default='1', verbose_name='URL неуспешной оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер транзакции оператора'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_amount',
            field=models.FloatField(verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_currency',
            field=models.PositiveIntegerField(choices=[(643, 'Рубли'), (10643, 'Тестовая валюта')], default=643, verbose_name='Валюта платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_code',
            field=models.CharField(blank=True, max_length=33, null=True, verbose_name='Номер виртуального счета'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('AB', 'Альфа-Клик'), ('AC', 'Банковская карта'), ('GP', 'Наличные через терминал'), ('MA', 'MasterPass'), ('MC', 'Мобильная коммерция'), ('PB', 'Интернет-банк Промсвязьбанка'), ('PC', 'Кошелек Яндекс.Денег'), ('SB', 'Сбербанк Онлайн'), ('WM', 'Кошелек WebMoney'), ('QW', 'QiWi кошелёк')], default='PC', max_length=2, verbose_name='Способ платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='performed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='scid',
            field=models.PositiveIntegerField(default='1', verbose_name='Номер витрины'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shop_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='За вычетом коммиссии', max_digits=15, null=True, verbose_name='Сумма полученная на р/с'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shop_currency',
            field=models.PositiveIntegerField(blank=True, choices=[(643, 'Рубли'), (10643, 'Тестовая валюта')], default=643, null=True, verbose_name='Валюта полученная на р/с'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shop_id',
            field=models.PositiveIntegerField(default='1', verbose_name='ID магазина'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('hold', 'Hold'), ('cancel', 'Cancel'), ('success', 'Success'), ('fail', 'Fail')], default='processed', max_length=16, verbose_name='Результата'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='success_url',
            field=models.URLField(default='1', verbose_name='URL успешной оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
